#ifndef HASH_TABLE_VALUE_TYPE
    #error HASH_TABLE_VALUE_TYPE need to be defined with a type specified (Ex. int, long, double, float, struct TestStruct, ...)
#endif

#include <stdint.h>
#ifndef INDEX_TYPE
    #define INDEX_TYPE int64_t
#endif
#include <stdbool.h>

#define MAKE_HASH_TABLE_NAME(x) hash_table_ ## x
#define HASH_TABLE_NAME(x) MAKE_HASH_TABLE_NAME(x)
#define HASH_TABLE HASH_TABLE_NAME(HASH_TABLE_VALUE_TYPE)

typedef struct HASH_TABLE HASH_TABLE;

#define MAKE_HASH_TABLE_NEW_NAME(x) x ## _new()
#define GEN_HASH_TABLE_NEW_NAME(x) MAKE_HASH_TABLE_NEW_NAME(x)
HASH_TABLE* GEN_HASH_TABLE_NEW_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_DESTROY_NAME(x) x ## _destroy(x* this)
#define GEN_HASH_TABLE_DESTROY_NAME(x) MAKE_HASH_TABLE_DESTROY_NAME(x)
void GEN_HASH_TABLE_DESTROY_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_GET_NAME(x) x ## _get(x* this, const char* key)
#define GEN_HASH_TABLE_GET_NAME(x) MAKE_HASH_TABLE_GET_NAME(x)
HASH_TABLE_VALUE_TYPE* GEN_HASH_TABLE_GET_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_REMOVE_NAME(x) x ## _remove(x* this, const char* key)
#define GEN_HASH_TABLE_REMOVE_NAME(x) MAKE_HASH_TABLE_REMOVE_NAME(x)
bool GEN_HASH_TABLE_REMOVE_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_SET_NAME(x) x ## _set(x* this, const char* key, HASH_TABLE_VALUE_TYPE value)
#define GEN_HASH_TABLE_SET_NAME(x) MAKE_HASH_TABLE_SET_NAME(x)
const char* GEN_HASH_TABLE_SET_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_GETCOUNT_NAME(x) x ## _getcount(x* this)
#define GEN_HASH_TABLE_GETCOUNT_NAME(x) MAKE_HASH_TABLE_GETCOUNT_NAME(x)
INDEX_TYPE GEN_HASH_TABLE_GETCOUNT_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_ITERATOR_NAME(x) hash_table_iterator_ ## x
#define HASH_TABLE_ITERATOR_NAME(x) MAKE_HASH_TABLE_ITERATOR_NAME(x)
#define HASH_TABLE_ITERATOR HASH_TABLE_ITERATOR_NAME(HASH_TABLE_VALUE_TYPE)

typedef struct {
    const char* key;
    HASH_TABLE_VALUE_TYPE value;
    HASH_TABLE* _table;
    INDEX_TYPE _index;
} HASH_TABLE_ITERATOR;

#define MAKE_HASH_TABLE_GETITERATOR_NAME(x) x ## _getiterator(x* this)
#define GEN_HASH_TABLE_GETITERATOR_NAME(x) MAKE_HASH_TABLE_GETITERATOR_NAME(x)
HASH_TABLE_ITERATOR GEN_HASH_TABLE_GETITERATOR_NAME(HASH_TABLE);

#define MAKE_HASH_TABLE_ITERATOR_NEXT_NAME(x, y) x ## _iterator_next(y* iterator)
#define GEN_HASH_TABLE_ITERATOR_NEXT_NAME(x, y) MAKE_HASH_TABLE_ITERATOR_NEXT_NAME(x, y)
bool GEN_HASH_TABLE_ITERATOR_NEXT_NAME(HASH_TABLE, HASH_TABLE_ITERATOR);

#undef GEN_HASH_TABLE_ITERATOR_NEXT_NAME
#undef MAKE_HASH_TABLE_ITERATOR_NEXT_NAME
#undef GEN_HASH_TABLE_GETITERATOR_NAME
#undef MAKE_HASH_TABLE_GETITERATOR_NAME
#undef HASH_TABLE_ITERATOR
#undef HASH_TABLE_ITERATOR_NAME
#undef MAKE_HASH_TABLE_ITERATOR_NAME
#undef GEN_HASH_TABLE_GETCOUNT_NAME
#undef MAKE_HASH_TABLE_GETCOUNT_NAME
#undef GEN_HASH_TABLE_SET_NAME
#undef MAKE_HASH_TABLE_SET_NAME
#undef GEN_HASH_TABLE_GET_NAME
#undef MAKE_HASH_TABLE_GET_NAME
#undef GEN_HASH_TABLE_DESTROY_NAME
#undef MAKE_HASH_TABLE_DESTROY_NAME
#undef GEN_HASH_TABLE_NEW_NAME
#undef MAKE_HASH_TABLE_NEW_NAME
#undef HASH_TABLE
#undef HASH_TABLE_NAME
#undef MAKE_HASH_TABLE_NAME
#undef HASH_TABLE_VALUE_TYPE
#undef MAKE_HASH_TABLE_REMOVE_NAME
#undef GEN_HASH_TABLE_REMOVE_NAME